title: Artizzi's Moonlight
tagline: Projects
description: A workshop of odd ideasâ€¦ fueled by code and a bit of chaos.
author: Artizzi
repository: Artizzi/artizzi.github.io
credits: https://artizzi.github.io/art/
url: https://artizzi.github.io
social:
  name: Artizzi
  links:
    - https://github.com/Artizzi
    - https://www.twitch.tv/artizzi_k
